/******************************************************************************
 *
 * Module: Main
 *
 * File Name: main.c
 *
 * Description: Main file for the Ultrasonic Project
 *
 * Author: Shehab Kishta
 *
 *******************************************************************************/
#include "icu.h"
#include "ultrasonic.h"
#include "lcd.h"
#include "std_types.h"
#include <avr/io.h>

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
Icu_ConfigType Icu_Config = {F_CPU_8,RISING};
uint8 g_counter = 0;
uint16 g_upTime = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
 * Description
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_counter++;
	if(g_counter == 1)
	{
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_counter == 2)
	{
		g_upTime = Icu_getInputCaptureValue();
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(RISING);
	}
}
int main(void)
{
	uint16 result = 0;
	/* Enable Interrupt */
	SREG |= (1<<7);
	Ultrasonic_init();
	LCD_init();
	LCD_displayString("Distance = ");

	while(1)
	{
		LCD_moveCursor(0, 11);
		/* Store the distance in a variable */
		result =  Ultrasonic_readDistance();
		LCD_intgerToString(result);
		LCD_displayString("cm ");
	}
}
